version: '3.8'

services:
  client:
    image: link-sharing-app-client5:latest
    # temp
    ports:
      - target: 3000
        published: 3001
        mode: host
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
# temp
# networks:
#   default:
#     name: portfolio_network
#     external: true
