version: '3.8'

services:
  client:
    image: link-sharing-app-client:latest
    ports:
      - target: 3000
        published: 3001
        mode: host
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
